[tool.poetry]
name = "contextual-spacing"
version = "0.1.0"
description = ""
authors = ["Koji Ishii <kojii@chromium.org>"]

[tool.poetry.dependencies]
python = "^3.8"
fonttools = "^4.20.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
